"""Service registry constants — maps service names to module/class paths.

Separated from ``__runtime__.py`` so the registry is testable without
instantiating the full Runtime.
"""

from __future__ import annotations

__all__ = [
    "SERVICE_CLASSES",
    "SERVICE_MAP",
    "WIRING",
]

# Maps service name -> (module_path, class_name)
SERVICE_MAP: dict[str, str] = {
    "mechanism": "underwrite.services.mechanism.service",
    "audit": "underwrite.services.audit.service",
    "quote": "underwrite.services.quote.service",
    "risk": "underwrite.services.risk.service",
    "fraud": "underwrite.services.fraud.service",
    "compliance": "underwrite.services.compliance.service",
    "npa": "underwrite.services.npa.service",
    "collateral": "underwrite.services.collateral.service",
    "recovery": "underwrite.services.recovery.service",
    "governance": "underwrite.services.governance.service",
    "graph": "underwrite.services.graph.service",
    "identity": "underwrite.services.identity.service",
    "notification": "underwrite.services.notification.service",
    "reporting": "underwrite.services.reporting.service",
    "underwriter": "underwrite.services.underwriter.service",
    "pricing": "underwrite.services.pricing.service",
    "document": "underwrite.services.document.service",
    "disbursement": "underwrite.services.disbursement.service",
    "collection": "underwrite.services.collection.service",
    "settlement": "underwrite.services.settlement.service",
    "origination": "underwrite.services.origination.service",
    "servicing": "underwrite.services.servicing.service",
    "payment": "underwrite.services.payment.service",
    "communication": "underwrite.services.communication.service",
    "workflow": "underwrite.services.workflow.service",
    "decision": "underwrite.services.decision.service",
    "fee": "underwrite.services.fee.service",
    "statement": "underwrite.services.statement.service",
}

SERVICE_CLASSES: dict[str, str] = {
    "mechanism": "MechanismService",
    "audit": "AuditService",
    "quote": "QuoteService",
    "risk": "RiskService",
    "fraud": "FraudService",
    "compliance": "ComplianceService",
    "npa": "NPAService",
    "collateral": "CollateralService",
    "recovery": "RecoveryService",
    "governance": "GovernanceService",
    "graph": "GraphService",
    "identity": "IdentityService",
    "notification": "NotificationService",
    "reporting": "ReportingService",
    "underwriter": "UnderwriterService",
    "pricing": "PricingService",
    "document": "DocumentService",
    "disbursement": "DisbursementService",
    "collection": "CollectionService",
    "settlement": "SettlementService",
    "origination": "OriginationService",
    "servicing": "ServicingService",
    "payment": "PaymentService",
    "communication": "CommunicationService",
    "workflow": "WorkflowService",
    "decision": "DecisionService",
    "fee": "FeeService",
    "statement": "StatementService",
}

WIRING: dict[str, list[str]] = {
    "seed.added": ["audit", "origination"],
    "user.added": ["audit", "fraud", "compliance", "risk", "origination"],
    "loan.originated": [
        "audit", "fraud", "risk", "npa", "collateral", "collection",
        "servicing", "payment", "fee"
    ],
    "repaid": ["audit", "fraud", "collection", "payment", "servicing"],
    "default.occurred": [
        "audit", "npa", "collateral", "recovery", "settlement", "workflow"
    ],
    "revoked": ["audit", "graph"],
    "quote.calculated": ["audit", "pricing"],
    "kyc.verified": ["audit", "compliance", "workflow"],
    "kyc.rejected": ["audit", "compliance", "notification", "workflow"],
    "aml.cleared": ["audit", "compliance"],
    "aml.frozen": ["audit", "compliance", "notification"],
    "fraud.alert": ["audit", "notification", "decision"],
    "fraud.wash.flag": ["audit", "notification", "decision"],
    "fraud.velocity.flag": ["audit", "notification", "decision"],
    "risk.scored": ["audit", "underwriter", "decision"],
    "risk.early_warning": ["audit", "notification", "servicing"],
    "npa.bucket.changed": ["audit", "notification", "collection"],
    "dlg.triggered": ["audit", "notification", "recovery"],
    "collateral.marked": ["audit"],
    "collateral.liquidated": ["audit", "settlement"],
    "governance.proposal": ["governance"],
    "governance.executed": ["audit", "governance"],
    "recovery.started": ["audit", "workflow"],
    "recovery.completed": ["audit", "settlement"],
    "identity.registered": ["audit", "identity"],
    "identity.rotated": ["audit", "identity"],
    "notification.sent": ["audit", "communication"],
    "report.generated": ["audit", "reporting"],
    "underwriter.approved": ["audit", "document", "disbursement", "workflow"],
    "underwriter.rejected": ["audit", "notification", "workflow"],
    "pricing.computed": ["audit", "quote", "document"],
    "document.generated": ["audit", "disbursement", "communication"],
    "disbursement.processed": ["audit", "servicing"],
    "collection.updated": ["audit", "statement", "fee"],
    "settlement.completed": ["audit", "servicing", "reporting"],
    "origination.created": ["audit", "underwriter", "workflow"],
    "origination.submitted": ["audit", "risk", "fraud", "compliance"],
    "payment.received": ["audit", "collection", "servicing", "statement"],
    "payment.due": ["audit", "notification", "communication"],
    "payment.overdue": ["audit", "collection", "fee", "notification"],
    "fee.assessed": ["audit", "statement"],
    "statement.generated": ["audit", "communication"],
    "workflow.started": ["audit"],
    "workflow.completed": ["audit", "notification"],
    "decision.made": ["audit", "underwriter", "workflow"],
}
