"""Service registry constants — maps service names to module/class paths.

Separated from ``__runtime__.py`` so the registry is testable without
instantiating the full Runtime.
"""

from __future__ import annotations

from underwrite.events import EventType

__all__ = [
    "HANDLER_CLASSES",
    "HANDLER_MAP",
    "WIRING",
]

# Maps service name -> (module_path, class_name)
HANDLER_MAP: dict[str, str] = {
    "mechanism": "underwrite.services.mechanism.handler",
    "audit": "underwrite.services.audit.handler",
    "quote": "underwrite.services.quote.handler",
    "risk": "underwrite.services.risk.handler",
    "fraud": "underwrite.services.fraud.handler",
    "compliance": "underwrite.services.compliance.handler",
    "npa": "underwrite.services.npa.handler",
    "collateral": "underwrite.services.collateral.handler",
    "recovery": "underwrite.services.recovery.handler",
    "governance": "underwrite.services.governance.handler",
    "graph": "underwrite.services.graph.handler",
    "identity": "underwrite.services.identity.handler",
    "notification": "underwrite.services.notification.handler",
    "reporting": "underwrite.services.reporting.handler",
    "underwriter": "underwrite.services.underwriter.handler",
    "pricing": "underwrite.services.pricing.handler",
    "document": "underwrite.services.document.handler",
    "disbursement": "underwrite.services.disbursement.handler",
    "collection": "underwrite.services.collection.handler",
    "settlement": "underwrite.services.settlement.handler",
    "origination": "underwrite.services.origination.handler",
    "servicing": "underwrite.services.servicing.handler",
    "payment": "underwrite.services.payment.handler",
    "communication": "underwrite.services.communication.handler",
    "workflow": "underwrite.services.workflow.handler",
    "decision": "underwrite.services.decision.handler",
    "fee": "underwrite.services.fee.handler",
    "statement": "underwrite.services.statement.handler",
    "prepayment": "underwrite.services.prepayment.handler",
    "kfs": "underwrite.services.kfs.handler",
    "razorpay": "underwrite.services.razorpay.handler",
    "consent": "underwrite.services.consent.handler",
    "dsr": "underwrite.services.dsr.handler",
    "credit_bureau": "underwrite.services.credit_bureau.handler",
}

HANDLER_CLASSES: dict[str, str] = {
    "mechanism": "MechanismHandler",
    "audit": "AuditHandler",
    "quote": "QuoteHandler",
    "risk": "RiskHandler",
    "fraud": "FraudHandler",
    "compliance": "ComplianceHandler",
    "npa": "NPAHandler",
    "collateral": "CollateralHandler",
    "recovery": "RecoveryHandler",
    "governance": "GovernanceHandler",
    "graph": "GraphHandler",
    "identity": "IdentityHandler",
    "notification": "NotificationHandler",
    "reporting": "ReportingHandler",
    "underwriter": "UnderwriterHandler",
    "pricing": "PricingHandler",
    "document": "DocumentHandler",
    "disbursement": "DisbursementHandler",
    "collection": "CollectionHandler",
    "settlement": "SettlementHandler",
    "origination": "OriginationHandler",
    "servicing": "ServicingHandler",
    "payment": "PaymentHandler",
    "communication": "CommunicationHandler",
    "workflow": "WorkflowHandler",
    "decision": "DecisionHandler",
    "fee": "FeeHandler",
    "statement": "StatementHandler",
    "prepayment": "PrepaymentHandler",
    "kfs": "KfsHandler",
    "razorpay": "RazorpayHandler",
    "consent": "ConsentHandler",
    "dsr": "DataSubjectRightsHandler",
    "credit_bureau": "CreditBureauHandler",
}

WIRING: dict[str, list[str]] = {
    EventType.SEED_ADDED.value: ["audit", "origination"],
    EventType.USER_ADDED.value: ["audit", "fraud", "compliance", "risk", "origination"],
    EventType.LOAN_ORIGINATED.value: [
        "audit",
        "fraud",
        "risk",
        "npa",
        "collateral",
        "collection",
        "servicing",
        "payment",
        "fee",
    ],
    EventType.REPAID.value: ["audit", "fraud", "collection", "payment", "servicing"],
    EventType.DEFAULT_OCCURRED.value: ["audit", "npa", "collateral", "recovery", "settlement", "workflow"],
    EventType.REVOKED.value: ["audit", "graph"],
    EventType.QUOTE_CALCULATED.value: ["audit", "pricing"],
    EventType.KYC_VERIFIED.value: ["audit", "compliance", "workflow"],
    EventType.KYC_REJECTED.value: ["audit", "compliance", "notification", "workflow"],
    EventType.AML_CLEARED.value: ["audit", "compliance"],
    EventType.AML_FROZEN.value: ["audit", "compliance", "notification"],
    EventType.FRAUD_ALERT.value: ["audit", "notification", "decision"],
    EventType.WASH_FLAG.value: ["audit", "notification", "decision"],
    EventType.VELOCITY_FLAG.value: ["audit", "notification", "decision"],
    EventType.RISK_SCORED.value: ["audit", "underwriter", "decision"],
    EventType.RISK_EARLY_WARNING.value: ["audit", "notification", "servicing"],
    EventType.NPA_BUCKET_CHANGED.value: ["audit", "notification", "collection", "reporting"],
    EventType.DLG_TRIGGERED.value: ["audit", "notification", "recovery"],
    EventType.SMA_CLASSIFIED.value: ["audit", "notification", "collection"],
    EventType.PROVISIONING_COMPUTED.value: ["audit", "reporting", "collection"],
    EventType.INCOME_RECOGNITION_SUSPENDED.value: ["audit", "servicing", "notification"],
    EventType.COLLATERAL_MARKED.value: ["audit"],
    EventType.COLLATERAL_LIQUIDATED.value: ["audit", "settlement"],
    EventType.GOVERNANCE_PROPOSAL.value: ["governance"],
    EventType.GOVERNANCE_EXECUTED.value: ["audit", "governance"],
    EventType.RECOVERY_STARTED.value: ["audit", "workflow"],
    EventType.RECOVERY_COMPLETED.value: ["audit", "settlement"],
    EventType.IDENTITY_REGISTERED.value: ["audit", "identity"],
    EventType.IDENTITY_ROTATED.value: ["audit", "identity"],
    EventType.NOTIFICATION_SENT.value: ["audit", "communication"],
    EventType.REPORT_GENERATED.value: ["audit", "reporting"],
    EventType.UNDERWRITER_APPROVED.value: ["audit", "document", "disbursement", "workflow"],
    EventType.UNDERWRITER_REJECTED.value: ["audit", "notification", "workflow"],
    EventType.UNDERWRITER_CONDITIONAL_APPROVED.value: ["audit", "notification", "workflow"],
    EventType.UNDERWRITER_REVIEW.value: ["audit", "notification", "workflow"],
    EventType.UNDERWRITER_ESCALATED.value: ["audit", "notification", "workflow"],
    EventType.UNDERWRITE_RULE_VIOLATED.value: ["audit", "notification"],
    EventType.PRICING_COMPUTED.value: ["audit", "quote", "document"],
    EventType.DOCUMENT_GENERATED.value: ["audit", "disbursement", "communication"],
    EventType.DISBURSEMENT_PROCESSED.value: ["audit", "servicing"],
    EventType.COLLECTION_UPDATED.value: ["audit", "statement", "fee"],
    EventType.SETTLEMENT_COMPLETED.value: ["audit", "servicing", "reporting"],
    EventType.ORIGINATION_CREATED.value: ["audit", "underwriter", "workflow"],
    EventType.ORIGINATION_SUBMITTED.value: ["audit", "risk", "fraud", "compliance"],
    EventType.PAYMENT_RECEIVED.value: ["audit", "collection", "servicing", "statement"],
    EventType.PAYMENT_DUE.value: ["audit", "notification", "communication"],
    EventType.PAYMENT_OVERDUE.value: ["audit", "collection", "fee", "notification"],
    EventType.FEE_ASSESSED.value: ["audit", "statement"],
    EventType.PENAL_INTEREST_ASSESSED.value: ["audit", "fee", "statement"],
    EventType.PREPAYMENT_REQUEST.value: ["audit", "prepayment"],
    EventType.PREPAYMENT_PROCESSED.value: ["audit", "servicing", "payment", "collection", "statement"],
    EventType.FORECLOSURE_COMPUTED.value: ["audit", "prepayment", "statement"],
    EventType.KFS_GENERATE.value: ["audit", "kfs"],
    EventType.KFS_GENERATED.value: ["audit", "communication", "document"],
    EventType.STATEMENT_GENERATED.value: ["audit", "communication"],
    EventType.RAZORPAY_ORDER_CREATE.value: ["audit", "razorpay"],
    EventType.RAZORPAY_ORDER_CREATED.value: ["audit", "payment", "servicing"],
    EventType.RAZORPAY_SUBSCRIBE.value: ["audit", "razorpay"],
    EventType.RAZORPAY_PAYMENT_CAPTURED.value: ["audit", "payment", "servicing", "collection", "notification"],
    EventType.RAZORPAY_PAYMENT_FAILED.value: ["audit", "notification"],
    EventType.RAZORPAY_PAYMENT_REFUNDED.value: ["audit", "payment", "servicing"],
    EventType.RAZORPAY_SUBSCRIPTION_CREATED.value: ["audit", "notification"],
    EventType.RAZORPAY_SUBSCRIPTION_CHARGED.value: ["audit", "payment", "servicing", "collection"],
    EventType.RAZORPAY_SUBSCRIPTION_FAILED.value: ["audit", "notification"],
    EventType.RAZORPAY_MANDATE_ACTIVE.value: ["audit", "servicing", "notification"],
    EventType.RAZORPAY_MANDATE_INACTIVE.value: ["audit", "notification"],
    EventType.RAZORPAY_WEBHOOK_RECEIVED.value: ["audit", "razorpay"],
    EventType.CONSENT_RECORDED.value: ["audit", "consent"],
    EventType.CONSENT_WITHDRAWN.value: ["audit", "consent"],
    EventType.CONSENT_EXPIRED.value: ["audit", "consent", "notification"],
    EventType.DSR_REQUEST.value: ["audit", "dsr"],
    EventType.DSR_REQUESTED.value: ["audit", "notification"],
    EventType.DSR_FULFILLED.value: ["audit", "dsr", "notification"],
    EventType.DSR_REJECTED.value: ["audit", "dsr", "notification"],
    EventType.GRIEVANCE_LOGGED.value: ["audit", "dsr"],
    EventType.GRIEVANCE_RESOLVED.value: ["audit", "dsr", "notification"],
    EventType.BREACH_DETECTED.value: ["audit", "dsr", "notification"],
    EventType.BREACH_NOTIFIED.value: ["audit", "notification"],
    EventType.BREACH_CLOSED.value: ["audit", "dsr"],
    EventType.DATA_PURGED.value: ["audit", "dsr"],
    EventType.DATA_ARCHIVED.value: ["audit", "dsr"],
    EventType.WORKFLOW_STARTED.value: ["audit"],
    EventType.WORKFLOW_COMPLETED.value: ["audit", "notification"],
    EventType.DECISION_MADE.value: ["audit", "underwriter", "workflow"],
    EventType.CREDIT_BUREAU_CHECK.value: ["audit", "credit_bureau"],
    EventType.CREDIT_BUREAU_CHECKED.value: ["audit", "underwriter", "notification"],
    EventType.CREDIT_BUREAU_CHECK_FAILED.value: ["audit", "notification"],
    EventType.CKYC_VERIFY.value: ["audit", "credit_bureau"],
    EventType.CKYC_VERIFIED.value: ["audit", "compliance", "notification", "workflow"],
    EventType.CKYC_REJECTED.value: ["audit", "compliance", "notification", "workflow"],
    # Compliance — video KYC, AML risk levels
    EventType.AML_FLAGGED.value: ["audit", "compliance", "notification", "decision"],
    EventType.KYC_VIDEO_INITIATED.value: ["audit", "compliance", "notification"],
    EventType.KYC_VIDEO_VERIFIED.value: ["audit", "compliance", "workflow"],
    # Pricing — penal interest, foreclosure
    EventType.PRICING_PENAL_INTEREST.value: ["audit", "pricing"],
    EventType.PRICING_PENAL_INTEREST_COMPUTED.value: ["audit", "fee", "collection", "statement"],
    EventType.PRICING_FORECLOSURE.value: ["audit", "pricing"],
    EventType.PRICING_FORECLOSURE_COMPUTED.value: ["audit", "prepayment", "settlement"],
    # Recovery — progress events
    EventType.RECOVERY_OFFER.value: ["audit", "communication", "notification"],
    EventType.RECOVERY_OFFER_RESPONSE.value: ["audit", "recovery"],
    EventType.RECOVERY_ESCALATED.value: ["audit", "notification", "collection"],
    EventType.RECOVERY_PROGRESS.value: ["audit", "collection", "statement"],
}
